<a href="https://colab.research.google.com/github/yaninabusquet-prog/data_science_prueba/blob/main/CEP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Analisis de datos del CEP
### Sector Industrial Argentino

In [1]:
## Importación de librerías y dataset

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
url = "https://raw.githubusercontent.com/yaninabusquet-prog/data_science_prueba/refs/heads/main/Fichas%20CEP.csv"

df = pd.read_csv(url, sep=';')

In [6]:
df.head()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2376 entries, 0 to 2375
Data columns (total 14 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   anio                      2376 non-null   int64
 1   id_sector_productivo      2376 non-null   object
 2   nombre_sector_productivo  2376 non-null   object
 3   nombre_variable           2376 non-null   object
 4   valor                     2376 non-null   object
 5   unidad_medida             2376 non-null   object
 6   Viajes_Y_Turismo          0 non-null      float64
 7   concepto_desc             0 non-null      float64
 8   Socio                     0 non-null      float64
 9   ADUANA                    0 non-null      float64
 10  USO_ECONOMICO             0 non-null      float64
 11  Producto                  0 non-null      float64
 12  Provincia                 0 non-null      float64
 13  Macrobloque               2376 non-null   int64
dtypes: float64(7), int64(2), object(5)
memory usage: 260.0+ KB

In [8]:
df.columns

Index(['anio', 'id_sector_productivo', 'nombre_sector_productivo',
       'nombre_variable', 'valor', 'unidad_medida', 'Viajes_Y_Turismo',
       'concepto_desc', 'Socio', 'ADUANA', 'USO_ECONOMICO', 'Producto',
       'Provincia', 'Macrobloque'],
      dtype='object')

In [9]:
# Ver valores faltantes
df.isna().sum()

anio                           0
id_sector_productivo           0
nombre_sector_productivo       0
nombre_variable                0
valor                          0
unidad_medida                  0
Viajes_Y_Turismo            2376
concepto_desc               2376
Socio                       2376
ADUANA                      2376
USO_ECONOMICO               2376
Producto                    2376
Provincia                   2376
Macrobloque                    0
dtype: int64

In [10]:
# Estadísticas básicas
df.describe(include='all')

,anio,id_sector_productivo,nombre_sector_productivo,nombre_variable,valor,unidad_medida,Viajes_Y_Turismo,concepto_desc,Socio,ADUANA,USO_ECONOMICO,Producto,Provincia,Macrobloque
count,2376.000000,2376,2376,2376,2376,2376,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2376.000000
unique,NaN,22,22,10,2080,5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,D,INDUSTRIA_MANUFACTURERA,AR_PUESTOS,"0,3",Cantidad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,108,108,242,80,726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2015.907407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.046296
std,3.117329,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.843213
min,2011.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25%,2013.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
50%,2016.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.000000
75%,2019.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000
max,2021.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000